Repository jotoho/SchiffeVersenken, pull requests merged in 2022-01, with the labels that each got.

#49 The board refreshes now after every input
  include/output.hpp
  src/gamelogic.cpp
  src/output.cpp
Labels: enhancement

#50 Introduce Makefile build configuration
  .gitignore
  Makefile
  run.sh
Labels: enhancement

#51 Input translator now throws invalid_argument instead of ending the program
  src/gamelogic.cpp
  src/input.cpp
Labels: bug

#52 Hits and misses are now colored and display after each turn
  include/output.hpp
  src/gamelogic.cpp
  src/output.cpp
Labels: enhancement

#53 Lots of comments
  include/board-generator.hpp
  include/boardpoint.hpp
  include/fieldinfo.hpp
  include/gamelogic.hpp
  include/global-config.hpp
  include/input.hpp
  include/output.hpp
  src/ai.cpp
  src/board-generator.cpp
  src/boardpoint.cpp
  src/gamelogic.cpp
  src/input.cpp
  src/main.cpp
Labels: documentation

#54 Added a tutorial
  include/output.hpp
  src/main.cpp
  src/output.cpp
Labels: enhancement

#57 Fixes two very small bugs
  src/gamelogic.cpp
  src/output.cpp
Labels: bug

#66 Added health information to top of screen
  include/gamelogic.hpp
  include/output.hpp
  src/gamelogic.cpp
  src/output.cpp
Labels: enhancement

#63 Add hack into input.cpp to support gcc 7.5.0
  Makefile
  include/board-generator.hpp
  src/board-generator.cpp
  src/input.cpp
Labels: bug

#65 Expand README with updated compilation and usage instructions
  README.md
Labels: documentation

#68 Small refactoring in board generator code
  src/board-generator.cpp
Labels: refactoring
